### PR TITLE
Fix Windows terminal output and add console enhancement

### LINKED ISSUE #48: Fix Windows terminal output

### PR DESCRIPTION
**Pull request by julian-fuchs**
Fix #48

### CODE REVIEW

File: src/game/terminal/RealTerminal.cpp [hunk 1]
```diff
@@ -50,8 +57,12 @@ void RealTerminal::SetScreen(const std::wstring& content) {
 
 void RealTerminal::Initialise() {
 #ifdef _WIN32
+  SetConsoleTitle(title.c_str());
   _setmode(_fileno(stdout), _O_U16TEXT);
-  std::ios_base::sync_with_stdio(false);
+  CONSOLE_CURSOR_INFO info;
+  info.dwSize = 100;
```
Comment (DavidRisch) [inline src/game/terminal/RealTerminal.cpp:63]: Please add some comments explaing what these lines do.

File: src/game/terminal/RealTerminal.h [hunk 2]
```diff
@@ -3,13 +3,21 @@
...
+#endif
+
 #include "ITerminal.h"
 
 /**
  * \brief Uniform interface for the terminal input and output
  */
 class RealTerminal : public ITerminal {
  public:
+  static std::string title;
```
Comment (DavidRisch) [inline src/game/terminal/RealTerminal.h:17]: Why is this attribute public?

File: src/game/terminal/RealTerminal.h [hunk 3]
```diff
@@ -3,13 +3,21 @@
...
+#ifdef _WIN32
+  static HANDLE console;
```
Comment (DavidRisch) [inline src/game/terminal/RealTerminal.h:19]: Why is this attribute public?
Please use a more discripive name, maybe `console_handle`?
Is it necessary for this to be an attribute? Why wouldnt a local variable work?

**Review by DavidRisch — CHANGES_REQUESTED** [review]

File: src/game/terminal/RealTerminal.h (hunk 3 above)
Comment (julian-fuchs) [reply src/game/terminal/RealTerminal.h:19]: In terms of performance, it could be better to use an attribute instead of calling `GetStdHandle()` for each `Clear()`.

**Review by DavidRisch — APPROVED** [review]
